### ISSUE TITLE
Can I customize the position of text on the QR code?

### ISSUE THREAD

**Issue by dong-lufei** [gera2ld/qrcanvas#23]
The text currently added is in the middle by default, and I want it to be in the bottom line, or in the bottom margin

**Comment by gera2ld** [comment]
No if you mean at the bottom of the QR code (**inside the QR code**) as it is likely to break the QR code.
That being said, you can add anything at your own risk since it is just a canvas.

Here is an example to add extra text **outside the QR code**:

https://stackblitz.com/edit/qrcanvas?file=src%2FApp.tsx
